#%RAML 1.0
title: Authentication API
baseUri: http://localhost:4005
mediaType: application/json

/authentication:
    description: Authentication management

    /login:
        post:
            description: Authenticate user and generates token
            body:
                type: object
                properties:
                    email: string
                    password: string
    
    /validate:
        post:
            description: Check valid token
            body:
            	type: object
                properties:
                    token: string

    /email/{id}:
        put:
            description: Verifies user from email