version: '2'
services:
  couch_db:
    image: klaemo/couchdb:2.0.0
    ports:
      - '3000:5984'

  auth_ms:
    build: .
    environment:
      PORT: '5984'
      ROOT_URL: 'couch_db'
    ports:
      - '4005:4005'
    links:
      - couch_db