version: '2'
services:
  users_db:
    image: klaemo/couchdb:2.0.0
    ports:
      - '3000:5984'

  auth_ms:
    build: .
    environment:
      DB_PORT: '5984'
      DB_ROOT_URL: 'users_db'
      SECRET: 'ec6607e21b57ac2ccc5836754893ed33' # Put your own secret!
    ports:
      - '4005:4005'
    links:
      - users_db